// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLTpMH5FDnE1QiQl8KRuS_vUzfYeOSyFM',
    appId: '1:667913438777:web:28cf86c572621dd87fefe8',
    messagingSenderId: '667913438777',
    projectId: 'sim800-69cc7',
    authDomain: 'sim800-69cc7.firebaseapp.com',
    databaseURL: 'https://sim800-69cc7-default-rtdb.firebaseio.com',
    storageBucket: 'sim800-69cc7.appspot.com',
    measurementId: 'G-LSQK7KRXN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZEQBF7PM75nwEvpXsLDf_GU7FS2fOVeo',
    appId: '1:667913438777:android:3313d7ecedbc1cbf7fefe8',
    messagingSenderId: '667913438777',
    projectId: 'sim800-69cc7',
    databaseURL: 'https://sim800-69cc7-default-rtdb.firebaseio.com',
    storageBucket: 'sim800-69cc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAJz371yhdW9dobrL12_2l1p9SHcTdFKk',
    appId: '1:667913438777:ios:73839759687d39a87fefe8',
    messagingSenderId: '667913438777',
    projectId: 'sim800-69cc7',
    databaseURL: 'https://sim800-69cc7-default-rtdb.firebaseio.com',
    storageBucket: 'sim800-69cc7.appspot.com',
    iosBundleId: 'com.example.robotTambak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAJz371yhdW9dobrL12_2l1p9SHcTdFKk',
    appId: '1:667913438777:ios:73839759687d39a87fefe8',
    messagingSenderId: '667913438777',
    projectId: 'sim800-69cc7',
    databaseURL: 'https://sim800-69cc7-default-rtdb.firebaseio.com',
    storageBucket: 'sim800-69cc7.appspot.com',
    iosBundleId: 'com.example.robotTambak',
  );
}
